# Generated by Django 4.1.7 on 2023-02-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_upload_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='video',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
